package velhajogo;

public class Jogo extends javax.swing.JFrame {

    public boolean jogA=true;
    public boolean jogB=true;
    public int contpos=0;
    public int k=0,i=0;
    int op;
    public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal1 , diagonal2;
    
    String[][]posVetor=new String [3][3];     
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void verificaJogadorDaVez() {
        if(jogA&&jogB){
            this.op=1;
            jogA=false;
            jogB=true;
            Visor.setText("Vez do Jogador O");
        }else if(jogA && jogB ==false){
            this.op=1;
            jogA=false;
            jogB=true;
            Visor.setText("Vez do Jogador O");
        }else {
            this.op=2;
            jogA=true;
            jogB=false;
            Visor.setText("Vez do Jogador X");
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botao1 = new javax.swing.JButton();
        Botao2 = new javax.swing.JButton();
        Botao3 = new javax.swing.JButton();
        Botao4 = new javax.swing.JButton();
        Botao5 = new javax.swing.JButton();
        Botao6 = new javax.swing.JButton();
        Botao7 = new javax.swing.JButton();
        Botao8 = new javax.swing.JButton();
        Botao9 = new javax.swing.JButton();
        Reiniciar = new javax.swing.JButton();
        Visor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Botao1.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao1ActionPerformed(evt);
            }
        });

        Botao2.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao2ActionPerformed(evt);
            }
        });

        Botao3.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao3ActionPerformed(evt);
            }
        });

        Botao4.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao4ActionPerformed(evt);
            }
        });

        Botao5.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao5ActionPerformed(evt);
            }
        });

        Botao6.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao6ActionPerformed(evt);
            }
        });

        Botao7.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao7ActionPerformed(evt);
            }
        });

        Botao8.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao8ActionPerformed(evt);
            }
        });

        Botao9.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        Botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao9ActionPerformed(evt);
            }
        });

        Reiniciar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Reiniciar.setText("Reiniciar");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        Visor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Visor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Visor, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpaPosicoes() {
        for(i=0;i<3;i++) {
        for(k=0;k<3;k++){
            posVetor[i][k] = "";
        } 
        }
        
    }
    
    public void desativaBotoes(){
        Botao1.setEnabled(false);
        Botao2.setEnabled(false);
        Botao3.setEnabled(false);
        Botao4.setEnabled(false);
        Botao5.setEnabled(false);
        Botao6.setEnabled(false);
        Botao7.setEnabled(false);
        Botao8.setEnabled(false);
        Botao9.setEnabled(false);
        
    }
    
    public void verificaPosicoes(){
        contpos=0;
        for(i=0;i<3;i++) {
        for(k=0;k<3;k++){
            if(posVetor[i][k] == "x" | posVetor[i][k] == "o"){
                contpos+=1;
            }
        } 
        }
    }
    
    public void verificaVencedor(){
        linha1 = posVetor[0][0] + posVetor[0][1] + posVetor [0][2];
        linha2 = posVetor[1][0] + posVetor[1][1] + posVetor [1][2];
        linha3 = posVetor[2][0] + posVetor[2][1] + posVetor [2][2];
        
        coluna1 = posVetor[0][0] + posVetor[1][0] + posVetor [2][0];
        coluna2 = posVetor[0][1] + posVetor[1][1] + posVetor [2][1];
        coluna3 = posVetor[0][2] + posVetor[1][2] + posVetor [2][2];
        
        diagonal1 = posVetor[0][0] + posVetor[1][1] + posVetor [2][2];
        diagonal2 = posVetor[0][2] + posVetor[1][1] + posVetor [2][0];
        
        if(linha1.equals("xxx") | linha2.equals("xxx") | linha3.equals("xxx") | coluna1.equals("xxx") | coluna2.equals("xxx") | coluna3.equals("xxx") | diagonal1.equals("xxx") | diagonal2.equals("xxx")){
            Visor.setText("O Vencedor é o X");
            desativaBotoes();
        }
        else if(linha1.equals("ooo") | linha2.equals("ooo")| linha3.equals("ooo") | coluna1.equals("ooo") | coluna2.equals("ooo") | coluna3.equals("ooo") | diagonal1.equals("ooo") | diagonal2.equals("ooo")){
            Visor.setText("O Vencedor é o O");
            desativaBotoes();
        }else if(contpos==9){
            Visor.setText("Não Houve Vencedor");
        }

    }
    private void Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao1ActionPerformed
        verificaJogadorDaVez();
        if(op==1){
           Botao1.setText("X"); 
           posVetor[0][0]="x";
        }else {
           Botao1.setText("O"); 
           posVetor[0][0]="o";
        }
        Botao1.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao1ActionPerformed

    private void Botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao2ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao2.setText("X"); 
           posVetor[0][1]="x";
        }else {
           Botao2.setText("O"); 
           posVetor[0][1]="o";
        }
        Botao2.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao2ActionPerformed

    private void Botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao3ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao3.setText("X"); 
           posVetor[0][2]="x";
        }else {
           Botao3.setText("O"); 
           posVetor[0][2]="o";
        }
        Botao3.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao3ActionPerformed

    private void Botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao4ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao4.setText("X"); 
           posVetor[1][0]="x";
        }else {
           Botao4.setText("O"); 
           posVetor[1][0]="o";
        }
        Botao4.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao4ActionPerformed

    private void Botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao5ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao5.setText("X"); 
           posVetor[1][1]="x";
        }else {
           Botao5.setText("O"); 
           posVetor[1][1]="o";
        }
        Botao5.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao5ActionPerformed

    private void Botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao6ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao6.setText("X"); 
           posVetor[1][2]="x";
        }else {
           Botao6.setText("O"); 
           posVetor[1][2]="o";
        }
        Botao6.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao6ActionPerformed

    private void Botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao7ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao7.setText("X"); 
           posVetor[2][0]="x";
        }else {
           Botao7.setText("O"); 
           posVetor[2][0]="o";
        }
        Botao7.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao7ActionPerformed

    private void Botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao8ActionPerformed
          verificaJogadorDaVez();
        if(op==1){
           Botao8.setText("X"); 
           posVetor[2][1]="x";
        }else {
           Botao8.setText("O"); 
           posVetor[2][1]="o";
        }
        Botao8.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao8ActionPerformed

    private void Botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao9ActionPerformed
        verificaJogadorDaVez();
        if(op==1){
           Botao9.setText("X"); 
           posVetor[2][2]="x";
        }else {
           Botao9.setText("O"); 
           posVetor[2][2]="o";
        }
        Botao9.setEnabled(false);
        
        verificaPosicoes();
        verificaVencedor();
        
    }//GEN-LAST:event_Botao9ActionPerformed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        Botao1.setText("");
        Botao1.setEnabled(true);
        Botao2.setText("");
        Botao2.setEnabled(true);
        Botao3.setText("");
        Botao3.setEnabled(true);
        Botao4.setText("");
        Botao4.setEnabled(true);
        Botao5.setText("");
        Botao5.setEnabled(true);
        Botao6.setText("");
        Botao6.setEnabled(true);
        Botao7.setText("");
        Botao7.setEnabled(true);
        Botao8.setText("");
        Botao8.setEnabled(true);
        Botao9.setText("");
        Botao9.setEnabled(true);
        limpaPosicoes();
        Visor.setText("");
        jogA=true;
        jogB=true;
    }//GEN-LAST:event_ReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao1;
    private javax.swing.JButton Botao2;
    private javax.swing.JButton Botao3;
    private javax.swing.JButton Botao4;
    private javax.swing.JButton Botao5;
    private javax.swing.JButton Botao6;
    private javax.swing.JButton Botao7;
    private javax.swing.JButton Botao8;
    private javax.swing.JButton Botao9;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JTextField Visor;
    // End of variables declaration//GEN-END:variables
}
